repository:
  description: "QA × SDET × LLM の実践ポートフォリオ。小さく完結した自動化パイプラインを公開。 / Practical QA × SDET × LLM portfolio featuring compact automation pipelines."
  homepage: https://ryosuke4219.github.io/portfolio/
  topics:
    - qa
    - sdet
    - playwright
    - llm
    - pytest
    - github-actions
    - devcontainers
    - codeql
