[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = [
  "node_modules",
  "packages",
  "projects/04-llm-adapter-shadow/.venv",
]

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = []

[tool.ruff.lint.isort]
force-single-line = false
known-first-party = ["llm_adapter"]

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
namespace_packages = true
mypy_path = ["projects/04-llm-adapter-shadow"]
explicit_package_bases = true
