[tool.black]
line-length = 120

[tool.ruff]
line-length = 180
target-version = "py311"
extend-exclude = [
  "node_modules",
  "packages",
  "projects/04-llm-adapter-shadow/.venv",
]

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = ["E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
known-first-party = ["adapter", "llm_adapter", "src.llm_adapter", "src", "tests"]
order-by-type = false
force-sort-within-sections = true

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
namespace_packages = true
mypy_path = ["projects/04-llm-adapter-shadow"]
explicit_package_bases = true

[tool.pytest.ini_options]
markers = [
    "asyncio: tests that drive asyncio event loops",
]
