provider: openai
endpoint: https://api.openai.com/v1/chat/completions
model: gpt-4.1-mini
auth_env: OPENAI_API_KEY
seed: 42
temperature: 0.2
top_p: 1.0
max_tokens: 512
timeout_s: 60
retries:
  max: 2
  backoff_s: 2
persist_output: false
pricing:
  prompt_usd: 0.005
  completion_usd: 0.015
rate_limit:
  rpm: 300
  tpm: 400000
quality_gates:
  determinism_diff_rate_max: 0.15
  determinism_len_stdev_max: 8
