name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.6.0
      - run: npm ci
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r projects/04-llm-adapter-shadow/requirements.txt
      - name: Run Node test suites
        run: |
          set -euxo pipefail
          npm run spec:validate
          npm run e2e:gen
          bash scripts/run-node-suite.sh
          npm run ci:analyze
          npm run ci:issue
          PYTHON=python3 node --test tests/e2e-shadow.test.mjs
      - name: Run Python tests
        run: |
          set -euxo pipefail
          pytest -q projects/04-llm-adapter-shadow/tests
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            junit-results.xml
            projects/03-ci-flaky/out
          if-no-files-found: warn
