# .github/workflows/ci.yml
name: portfolio-ci

on: [push, pull_request]

# 同じブランチで複数実行されたら古い方をキャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'   # ← npm依存キャッシュを有効化

      - name: Install deps & Playwright browsers
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          npx playwright install --with-deps

      - name: Validate cases JSON
        run: npm run spec:validate

      - name: Generate E2E tests
        run: npm run e2e:gen

      - name: Run Playwright
        run: npm test

      - name: Analyze JUnit
        if: always()
        run: npm run ci:analyze

      - name: Create issue (stub)
        if: always()
        run: npm run ci:issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (JUnit, DB, raw results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            junit-results.xml
            database.json
            test-results/**
