name: Coverage

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/04-llm-adapter-shadow/requirements.txt pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest -q \
            --cov=projects/04-llm-adapter-shadow/src \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov \
            projects/04-llm-adapter-shadow/tests

      - name: Prepare coverage bundle
        if: always()
        run: |
          set -euo pipefail
          mkdir -p reports/coverage
          if [ -d htmlcov ]; then
            cp -a htmlcov/. reports/coverage/
          fi
          if [ -f coverage.xml ]; then
            cp coverage.xml reports/coverage/coverage.xml
          fi

      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: reports/coverage/coverage.xml
          if-no-files-found: warn

      - name: Upload coverage Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          name: coverage-report
          path: reports
