name: Link Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lychee:
    name: Run lychee link checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-file .lycheeignore
            README.md
            docs/**/*.md
            projects/**/*.md
