name: Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - 'projects/**'
      - 'tools/**'
      - 'packages/**'
      - 'tests/**'
      - 'scripts/**'
      - 'eslint.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'pyproject.toml'
      - '.github/workflows/**'
      - 'docs/examples/**'
      - '!docs/**/*.md'
      - '!docs/**/*.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - 'projects/**'
      - 'tools/**'
      - 'packages/**'
      - 'tests/**'
      - 'scripts/**'
      - 'eslint.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'pyproject.toml'
      - '.github/workflows/**'
      - 'docs/examples/**'
      - '!docs/**/*.md'
      - '!docs/**/*.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.6.0

      - name: Install Node.js dependencies
        run: npm ci

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r projects/04-llm-adapter-shadow/requirements.txt ruff mypy black

      - name: Run npm lint
        run: npm run lint:js

      - name: Run ruff
        run: ruff check .

      - name: Run black
        run: black --check .

      - name: Run mypy
        run: mypy --config-file pyproject.toml projects/04-llm-adapter-shadow/src projects/04-llm-adapter-shadow/tests tools

      - name: Run compileall
        run: python -m compileall projects/04-llm-adapter-shadow
