name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  javascript:
    name: JavaScript lint & format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-progress

      - name: Run ESLint
        run: npm run lint:js

      - name: Verify formatting
        run: npm run format:check

  python:
    name: Python lint & type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: projects/04-llm-adapter-shadow/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/04-llm-adapter-shadow/requirements.txt
          pip install ruff mypy

      - name: Ruff lint
        run: ruff check projects/04-llm-adapter-shadow/src --output-format=full --fix --exit-non-zero-on-fix

      - name: Mypy type check
        run: mypy projects/04-llm-adapter-shadow/src --pretty --strict
