name: Publish Docs
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build docs
        run: |
          python3 tools/weekly_summary.py \
            --runs projects/03-ci-flaky/data/runs.jsonl \
            --flaky projects/03-ci-flaky/out/flaky_rank.csv \
            --out docs/weekly-summary.md \
            --days 7
          python3 tools/generate_gallery_snippets.py
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
