name: Publish Docs (GitHub Pages)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pages_enabled: ${{ steps.pages_status.outputs.actions_ready }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check GitHub Pages status
        id: pages_status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let buildType = "disabled";
            if (repo.has_pages) {
              try {
                const { data: pages } = await github.rest.repos.getPages({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                buildType = pages.build_type ?? "legacy";
              } catch (error) {
                if (error.status === 404) {
                  buildType = "not_configured";
                } else {
                  throw error;
                }
              }
            }

            const actionsReady = repo.has_pages && buildType === "workflow";
            core.setOutput("has_pages", String(repo.has_pages));
            core.setOutput("build_type", buildType);
            core.setOutput("actions_ready", String(actionsReady));

      - name: Setup Pages
        if: steps.pages_status.outputs.actions_ready == 'true'
        uses: actions/configure-pages@v3

      - name: Upload documentation artifact
        if: steps.pages_status.outputs.actions_ready == 'true'
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: GitHub Pages status notice
        if: steps.pages_status.outputs.actions_ready != 'true'
        run: |
          echo "GitHub Pages が未設定、もしくは 'GitHub Actions' 以外の配信方法になっています。"
          echo "Settings > Pages で GitHub Pages を有効化し、Build and deployment に 'GitHub Actions' を選択してください。"
          echo "現状ではドキュメントの自動デプロイはスキップされます。"

  deploy:
    if: needs.build.outputs.pages_enabled == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
