name: Publish Docs (GitHub Pages)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pages_enabled: ${{ steps.pages_status.outputs.has_pages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check GitHub Pages status
        id: pages_status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("has_pages", String(data.has_pages));

      - name: Setup Pages
        if: steps.pages_status.outputs.has_pages == 'true'
        uses: actions/configure-pages@v3

      - name: Upload documentation artifact
        if: steps.pages_status.outputs.has_pages == 'true'
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: GitHub Pages disabled notice
        if: steps.pages_status.outputs.has_pages != 'true'
        run: |
          echo "GitHub Pages is not enabled for this repository."
          echo "Enable it in the repository settings to activate automated deployments."

  deploy:
    if: needs.build.outputs.pages_enabled == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
