name: LLM Adapter Shadow (pytest)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: projects/04-llm-adapter-shadow/requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/04-llm-adapter-shadow/requirements.txt
      - name: Run tests
        run: |
          pytest -q --asyncio-mode=strict projects/04-llm-adapter-shadow/tests
